version: '3.8'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    env_file: .env
    expose:
        - 8080
    networks:
        - backend
  db: 
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_HOST: "%"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
networks:
  backend:
    driver: bridge
volumes:
  db_data: