version: '3.8'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.prod
    ports:
        - "8080:8080"
    restart: unless-stopped
    expose:
        - 8080
    networks:
        - backend
networks:
  backend:
    driver: bridge