version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    env_file: .env
    networks:
      - backend
    depends_on:
      db:
        condition: service_started
  # migrate:
  #   image: migrate/migrate
  #   command: ["-database", "mysql://root:root@tcp(db:3306)/sword", "-path", "/migrations", "up"]
  #   volumes:
  #     - $PWD/migrations:/migrations
  #   depends_on:
  #     db:
  #       condition: service_started
  #   networks:
  #     - backend
  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  db_data: