FROM golang:1.20-alpine3.17 AS builder
LABEL stage=builder
WORKDIR /desafio
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a

FROM scratch AS final
ARG ENV
WORKDIR /
COPY --from=builder /desafio/api .
CMD [ "./api" ]